language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./configurations/travis/miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f configurations/environment.yml

script:
  - source .envrc
  - pytest

  - flake8-nb; [ $? -eq 0 ] || exit 1
  - black-nb --check .; [ $? -eq 0 ] || exit 1

  - travis_wait run-notebooks
