name: ekw-lectures

channels:
  - defaults
  - opensourceeconomics
  - conda-forge

dependencies:
- pip
- numpy
- pandas>=0.24
- pytest
- jupyterlab
- matplotlib
- seaborn
- scipy
- estimagic>=1.2.0
- black
- numba
- flake8
- doc8
- restructuredtext_lint
- tox-conda
- respy>=2.1.1
- sphinx>=1.4
- nbsphinx
- pyarrow
- pytest-black
- pytest-flake8
- pre-commit
- pip:
    - black-nb
    - flake8-nb
    - sphinx_rtd_theme
    - numdifftools
    - nbsphinx
    - cairosvg
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - Py-BOBYQA


