name: ekw-lectures

channels:
  - defaults
  - opensourceeconomics
  - conda-forge

dependencies:
- pip
- numpy
- pandas>=0.24
- pytest=5.4.3
- jupyterlab
- matplotlib=3.2.
- seaborn
- scipy
- estimagic==0.0.31
- black
- numba==0.48.0
- flake8
- doc8
- pyarrow
- restructuredtext_lint
- tox-conda
- respy
- sphinx>=1.4
- nbsphinx
- pytest-black
- pytest-flake8
- pip:
    - black-nb
    - flake8-nb
    - sphinx_rtd_theme
    - numdifftools
    - nbsphinx
    - cairosvg
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
