name: ekw-lectures

channels:
  - defaults
  - opensourceeconomics
  - conda-forge

dependencies:
- pip
- numpy
- pandas
- pytest
- jupyterlab
- matplotlib
- seaborn
- scipy
- estimagic
- black
- numba
- flake8
- doc8
- restructuredtext_lint
- tox-conda
- respy>=2.1.1
- sphinx
- nbsphinx
- pyarrow
- pytest-black
- pytest-flake8
- pre-commit
- python_abi>=3.9
- pip:
    - black-nb
    - flake8-nb
    - sphinx_rtd_theme
    - numdifftools
    - nbsphinx
    - cairosvg
    - sphinxcontrib-bibtex
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - Py-BOBYQA
