name: respy-lectures

channels:
  - defaults
  - opensourceeconomics
  - conda-forge

dependencies:
- pip
- numpy
- pandas>=0.24
- pytest
- jupyterlab
- matplotlib
- seaborn
- scipy
- estimagic>=0.0.30
- black
- numba
- flake8
- doc8
- restructuredtext_lint
- tox-conda
- respy
- pytest-black
- pytest-flake8
- pip:
  - black-nb
  - flake8-nb
