name: hyperbolic_discounting
channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - ipykernel=5.1.3
  - jupyterlab=1.1.4
  - pip=19.2.3
  - python=3.7
  - python-graphviz=0.8
  - nb_conda_kernels=2.2.2
  - pandas>=1.0
  - numpy
  - scipy
  - seaborn>=0.10
  - jupyterlab
  - nbsphinx
  - pdbpp
  - xlrd
  - matplotlib
  - seaborn
  - utilities
  - fastparquet
  - respy
  - estimagic

  - pip:
    - click==7.0

    - pre-commit==1.18.3

    - matplotlib==3.1.1
    - nbsphinx==0.4.2
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3

    - sphinx==2.2.0
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==1.0.0
